[package]
name = "address-cmp"
version = "0.2.0"
authors = ["Xavientois <joshua.rampersad@hotmail.com>"]
description = "An attribute for address comparison"
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "1.0"
